### ISSUE TITLE
hxCodec randomly crashes when starting video

### ISSUE THREAD

**Issue by ActualMandM** [polybiusproxy/hxCodec#115]
Sometimes when trying to start playing a video, hxCodec will just crash instead. This started happening after libVLC was updated. (7947a857be5c21840c78d943815ef7756e280093)
```
[000001b3e6024160] main input error: ES_OUT_SET_(GROUP_)PCR  is called too late (pts_delay
```
https://user-images.githubusercontent.com/15317421/166993861-aac554e9-5e00-45f4-ab33-9988fa2f3cf5.mp4

**Comment by McJonnycat** [comment]
i like your wallpaper

**Comment by Jrgamer4u** [comment]
after a quick google search:

[it may be a problem with your video](https://stackoverflow.com/questions/31636150/vlclib-error-es-out-reset-pcr), or [it may be the framerate that's causing the problem.](https://github.com/waveform80/picamera/issues/248)

if it's 2 that's causing it, #65 or #70 may be of interest.

[this](https://github.com/ninjamuffin99/Funkin/pull/458/files), [this](https://lib.haxe.org/p/cacher/), and [this](https://lib.haxe.org/p/hotmem/) may also be of interest.

**Comment by polybiusproxy** [comment]
This should be fixed with the downgrading of the libraries, please test it again with the latest git version! @ActualMandM

**Comment by ActualMandM** [comment]
Tried the latest git version and the game now refuses to open.

**Comment by polybiusproxy** [comment]
> Tried the latest git version and the game now refuses to open.

Could you please provide the logs when crashing?

**Comment by ActualMandM** [comment]
It doesn't provide me anything, as the game simply refuses to open.

```
Link: ApplicationMain-debug.exe
   Creating library ApplicationMain-debug.lib and object ApplicationMain-debug.exp
The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command lime test windows -debug --haxelib=hxcpp-debug-server --connect 6000" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.
```

**Comment by Jrgamer4u** [comment]
the game is unable to start correctly for my windows 10 now; bro why is hxcodec the most fiddly thing on earth wtf

**Comment by polybiusproxy** [comment]
> the game is unable to start correctly for my windows 10 now; bro why is hxcodec the most fiddly thing on earth wtf

😢

**Comment by Jrgamer4u** [comment]
and this time no one knows what to fix cuz it doesn't even shows a error message it just says `it dont works lmao gl nerd [most common error code ever]`

**Comment by ActualMandM** [comment]
Trying it with `hxcpp-debug-server` enabled, no luck with error messages.

**Comment by ActualMandM** [comment]
The two crashes seem to no longer occur after doing a clean install of latest hxCodec git.
