### ISSUE TITLE
how do I do the VideoSprite? Im using Kade

### ISSUE THREAD

**Issue by TheRealJake12** [polybiusproxy/hxCodec#117]
ok so I accidently pressed ENTER so what the full title was gonna say was
how do I do the VideoSprite? Im using Kade's Stage System.

**Comment by Jrgamer4u** [comment]
im assuming that it's the same code but you replace VideoHandler to VideoSprite

```haxe
import vlc.VideoSprite;

var video:VideoSprite;
```
```haxe
video = new VideoSprite();
```

**Comment by TheRealJake12** [comment]
what are the arguments?

**Comment by Jrgamer4u** [comment]
idk
