### ISSUE TITLE
Video loud before it fully loads.

### ISSUE THREAD

**Issue by ACrazyTown** [polybiusproxy/hxCodec#122]
I have an issue with hxCodec (although an older version) where when the video plays, before there is any video ouput.
And when the video fully loads and starts displaying the volume syncs to HaxeFlixel's current volume.

How could I fix this? It's quite annoying since you literally get jumpscared by a video.

**Comment by polybiusproxy** [comment]
Try updating to the latest version.
Also, it may be due to the performance of the machine, on older versions of hxCodec, I did some tests with the vanilla FNF, and the playback went smooth.

**Comment by ACrazyTown** [comment]
yup, turns out that updating fixed it oops!
thx for your help

**Comment by polybiusproxy** [comment]
👍

**Comment by ACrazyTown** [comment]
Reopening this as I've found that the issue still persists, even with the newest haxelib release.

**Comment by MAJigsaw77** [comment]
can you show how the issue manifest?

**Comment by ACrazyTown** [comment]
> can you show how the issue manifest?

This is an example of it:

https://user-images.githubusercontent.com/47027981/212552827-666a82b2-33f2-4def-98c3-aae45f366d0d.mp4

I create the video with this code:
![image](https://user-images.githubusercontent.com/47027981/212552859-5c24a896-80bd-449b-9d04-63b36e272631.png)

Also I use the latest HaxeFlixel, Lime and OpenFL versions. But I believe the same issue happened when I was running Flixel 4.11.0, Lime 7.9.0 and OpenFL 9.1.0

**Comment by MAJigsaw77** [comment]
Weird but I think I can fix this

**Comment by MAJigsaw77** [comment]
@ACrazyTown see if the issue still persists with the latest commit.

**Comment by ACrazyTown** [comment]
Fixed by @4bbe980
