### ISSUE TITLE
errors, missing dll file?

### ISSUE THREAD

**Issue by Jrgamer4u** [polybiusproxy/hxCodec#123]
I had errors with VLC that i didn't know until using -debug, because it still ran. idk if it's from hxcodec or my video or my fnf mod.
here's what it spat out:
starting up
```
source/MusicBeatState.hx:20: reg (x: -200 | y: -200 | w: 3584 | h: 2016)
source/MusicBeatState.hx:20: reg (x: -200 | y: -200 | w: 3584 | h: 2016)
vlc/bitmap/VlcBitmap.hx:135: 2000
vlc/bitmap/VlcBitmap.hx:590: new width is 2000
vlc/bitmap/VlcBitmap.hx:155: 1125
vlc/bitmap/VlcBitmap.hx:610: new height is 1125
```
setting path
error 1
```
[00000227918530a0] mmdevice audio output error: cannot initialize COM (error 0x80010106)
```
alert box
```
The procedure entry point decode URL could not be located in the dynamic link library
…\export\debug\windows\bin\plugins\gui\libqt4_plugin.dll
```
start video
```
vlc/bitmap/VlcBitmap.hx:174: the video is playing
source/MusicBeatState.hx:20: reg (x: -200 | y: -200 | w: 3584 | h: 2016)
```
error 2
```
[00000227b09aedd0] main vout display error: Failed to set on top
[00000227b09d48b0] main vout display error: Failed to set on top
[00000227b09d37e0] main vout display error: Failed to set on top
```
vlc rendering stuff, when video is playing, no errors
disposing video
```
vlc/bitmap/VlcBitmap.hx:642: disposing the whole thing lol
```
error 3
```
[h264 @ 00000227a8b01ea0] get_buffer() failed
[h264 @ 00000227a8b01ea0] thread_get_buffer() failed
[h264 @ 00000227a8b01ea0] decode_slice_header error
[h264 @ 00000227a8b01ea0] no frame!
[h264 @ 00000227a8b4ef20] get_buffer() failed
[h264 @ 00000227a8b4ef20] thread_get_buffer() failed
[h264 @ 00000227a8b4ef20] decode_slice_header error
[h264 @ 00000227a8b4ef20] no frame!
```
pausing
```
vlc/bitmap/VlcBitmap.hx:628: the new volume is 1.4
vlc/bitmap/VlcBitmap.hx:438: new volume: 140
source/MusicBeatState.hx:20: reg (x: -200 | y: -200 | w: 3584 | h: 2016)
vlc/bitmap/VlcBitmap.hx:200: the video is pausing
```

**Comment by polybiusproxy** [comment]
added the missing dll, jigsaw seems to have messed up
try again, if it doesn't works, it may be your video

**Comment by jigsaw-4277821** [comment]
> added the missing dll, jigsaw seems to have messed up try again, if it doesn't works, it may be your video

Bruh I added all the plugins then VLC had, I didn't do anything to then

**Comment by polybiusproxy** [comment]
> > added the missing dll, jigsaw seems to have messed up try again, if it doesn't works, it may be your video
> 
> Bruh I added all the plugins then VLC had, I didn't do anything to them

then it may be that @Jrgamer4u is using an older version

**Comment by jigsaw-4277821** [comment]
> > > added the missing dll, jigsaw seems to have messed up try again, if it doesn't works, it may be your video
> > 
> > 
> > Bruh I added all the plugins then VLC had, I didn't do anything to them
> 
> then it may be that @Jrgamer4u is using an older version

Who knows

**Comment by Jrgamer4u** [comment]
im using the latest git version, and adding libqt4_plugin.dll didn't work?
uhh
it doesn't matter cuz it doesn't make hxcodec not work
:( sap

**Comment by polybiusproxy** [comment]
This should be fixed from now, please test it!
