### ISSUE TITLE
I Have No Idea!

### ISSUE THREAD

**Issue by TheRealJake12** [polybiusproxy/hxCodec#128]
![image](https://user-images.githubusercontent.com/84357907/171092253-f1961308-bd42-4b3c-8d25-f099b18107ce.png)

Gave me an error here I have 0 idea why

**Comment by polybiusproxy** [comment]
Seems to be an issue with the pixel data, so it may be your video.
If it keeps happening, let me know.

**Comment by TheRealJake12** [comment]
I love hxCodec and all but the older versions ran better imo. I might just use them for my projects. Feel Free to close this issue

**Comment by Jrgamer4u** [comment]
> I love hxCodec and all, but the older versions ran better imo. I might just use them for my projects. Feel Free to close this issue.

i'm pretty sure something happened when it became a haxelib, cuz when changing from the original version into the git haxelib my videos at the end of the song stopped working and still isn't working.

**Comment by polybiusproxy** [comment]
> > I love hxCodec and all, but the older versions ran better imo. I might just use them for my projects. Feel Free to close this issue.
> 
> i'm pretty sure something happened when it became a haxelib, cuz when changing from the original version into the git haxelib my videos at the end of the song stopped working and still isn't working.

Thanks for telling me, might be the libVLC update.

**Comment by polybiusproxy** [comment]
Will close this, if it keeps happening, re-open it.
