### ISSUE TITLE
Video Height is glitched

### ISSUE THREAD

**Issue by BeastlyGhost** [polybiusproxy/hxCodec#131]
happens with videos with a specific height, usually 4:3 videos do not have this problem
![image](https://user-images.githubusercontent.com/45212377/171930624-c4c571fc-7143-4e1c-80a2-d0919ec43104.png)

**Comment by polybiusproxy** [comment]
These issues started to appear once libVLC was updated :/
I might have to revert some changes...

**Comment by jigsaw-4277821** [comment]
> 

Dude that was happening even in android with the old libs, you have to fix this

**Comment by jigsaw-4277821** [comment]
The libs aren't the ploblem

**Comment by Stilic** [comment]
@polybiusproxy maybe we should rewrite hxcodec
or smth

**Comment by polybiusproxy** [comment]
> > 
> 
> Dude that was happening even in android with the old libs, you have to fix this

this wasn't designed for android in the first place :/
i can assure that it worked perfectly with the old libs

@BeastlyGhost What are the video dimensions?

**Comment by BeastlyGhost** [comment]
> > > 
> > 
> > 
> > Dude that was happening even in android with the old libs, you have to fix this
> 
> this wasn't designed for android in the first place :/ i can assure that it worked perfectly with the old libs
> 
> @BeastlyGhost What are the video dimensions?

1278x720

**Comment by polybiusproxy** [comment]
> > > > 
> > > 
> > > 
> > > Dude that was happening even in android with the old libs, you have to fix this
> > 
> > 
> > this wasn't designed for android in the first place :/ i can assure that it worked perfectly with the old libs
> > @BeastlyGhost What are the video dimensions?
> 
> 1278x720

1278 pixels, huh? It will definitely work at 1280x720 px, so try to resize it to that dimensions.

**Comment by polybiusproxy** [comment]
May I ask why it is 1278x720px in the first place?

**Comment by jigsaw-4277821** [comment]
> 

Datee said that the implementation will be for android so I done it already, just fix CPP and done

**Comment by jigsaw-4277821** [comment]
The function then is returning the pixel buffer is format setup

**Comment by jigsaw-4277821** [comment]
You should start from it

**Comment by BeastlyGhost** [comment]
> May I ask why it is 1278x720px in the first place?

yeah I don't think it made sense either while the team was working on the animation

**Comment by jigsaw-4277821** [comment]
@BeastlyGhost if this will be pushed that this hole issue will gone
https://github.com/polybiusproxy/hxCodec/pull/135

**Comment by polybiusproxy** [comment]
This has been fixed! Thanks for letting me know about this!
