### ISSUE TITLE
github workflows can't compile on linux

### ISSUE THREAD

**Issue by BeastlyGhost** [polybiusproxy/hxCodec#142]
apparently github workflows can't compile if hxCodec is active on a repository

![image](https://user-images.githubusercontent.com/45212377/174538880-05d748a7-cf6f-40a9-82c2-72b1b7b9460c.png)

I did some digging and apparently *something like this* can fix it

![image](https://user-images.githubusercontent.com/45212377/174538988-93d829d6-8482-4efd-a1e0-58258dc3fda2.png)

**Comment by TheRealJake12** [comment]
cool

**Comment by polybiusproxy** [comment]
> apparently github workflows can't compile if hxCodec is active on a repository
> 
> ![image](https://user-images.githubusercontent.com/45212377/174538880-05d748a7-cf6f-40a9-82c2-72b1b7b9460c.png)
> 
> I did some digging and apparently _something like this_ can fix it
> 
> ![image](https://user-images.githubusercontent.com/45212377/174538988-93d829d6-8482-4efd-a1e0-58258dc3fda2.png)

Strange, it compiles perfectly for me.

**Comment by TheRealJake12** [comment]
> apparently github workflows can't compile if hxCodec is active on a repository
> 
> ![image](https://user-images.githubusercontent.com/45212377/174538880-05d748a7-cf6f-40a9-82c2-72b1b7b9460c.png)
> 
> I did some digging and apparently _something like this_ can fix it
> 
> ![image](https://user-images.githubusercontent.com/45212377/174538988-93d829d6-8482-4efd-a1e0-58258dc3fda2.png)

I also have this error. [This](https://github.com/TheRealJake12/Kade-Engine-Community/runs/6945130323?check_suite_focus=true) is my GH run failure

**Comment by TheRealJake12** [comment]
ok seriously, how can we fix GH Actions. Its bugging me having the X as failed build

**Comment by TheRealJake12** [comment]
@BeastlyGhost make sure the linux version is ubuntu 22.04 and install these libraries

```
sudo apt-get update
sudo apt-get install gcc-multilib g++-multilib haxe -y
sudo apt-get install libvlc-dev
sudo apt-get install libvlccore-dev
sudo apt-get install vlc-bin
sudo apt-get -y install libidn12
```

**Comment by TheRealJake12** [comment]
@BeastlyGhost  you should close this

**Comment by BeastlyGhost** [comment]
thx
