### ISSUE TITLE
I have the Macos libs

### ISSUE THREAD

**Issue by BushTrain460615** [polybiusproxy/hxCodec#147]

**Comment by BushsHaxs** [comment]
if you want them I can give them to you

**Comment by trayfellow** [comment]
![image](https://user-images.githubusercontent.com/48515908/175866270-4ca8b634-befa-4cae-be33-fa4d2fb5b1e3.png)
got these files? if so make a pull request with them

**Comment by BushTrain460615** [comment]
I do

**Comment by BushTrain460615** [comment]
<img width="346" alt="Screen Shot 2022-06-27 at 12 53 38 AM" src="https://user-images.githubusercontent.com/72326501/175869019-6c3b2998-7c5d-4501-8fdc-feee99354b31.png">

**Comment by trayfellow** [comment]
> <img alt="Screen Shot 2022-06-27 at 12 53 38 AM" width="346" src="https://user-images.githubusercontent.com/72326501/175869019-6c3b2998-7c5d-4501-8fdc-feee99354b31.png">

you have a mac? if so we can try testing this

**Comment by BushTrain460615** [comment]
> > <img alt="Screen Shot 2022-06-27 at 12 53 38 AM" width="346" src="https://user-images.githubusercontent.com/72326501/175869019-6c3b2998-7c5d-4501-8fdc-feee99354b31.png">
> 
> you have a mac? if so we can try testing this

i do have a Mac I use it as my main OS
