### ISSUE TITLE
Linux crashes upon initialization

### ISSUE THREAD

**Issue by ActualMandM** [polybiusproxy/hxCodec#161]
When trying to initialize the VideoHandler on Linux, the game will just crash with no error message or dialog.

https://user-images.githubusercontent.com/15317421/178420649-b01b210d-c2b4-4714-90d9-22834de1811a.mp4

![image](https://user-images.githubusercontent.com/15317421/178420772-b8a0b7f5-a315-4c66-834f-a4033e758bcc.png)

I have both the libvlc and libidn libraries installed, as otherwise the game would fail to compile.

**Comment by trayfellow** [comment]
![Screenshot_20220713-042721_Chrome](https://user-images.githubusercontent.com/48515908/178598532-e34ecbe3-afb1-4fe1-9edb-ccc414bca081.jpg)

did u install these 3

**Comment by ActualMandM** [comment]
I can't use `apt-get`, so I've opted for `yay -S libvlc` (which also gets libvlccore) instead.

**Comment by ActualMandM** [comment]
Okay, installing vlc instead of libvlc worked. Odd...

**Comment by trayfellow** [comment]
> Okay, installing vlc instead of libvlc worked. Odd...
> 
> ![image](https://user-images.githubusercontent.com/15317421/178612580-1605b073-9aa1-40d9-b63f-b847e61f84f6.png)

wish there was a way of having hxcodec linux supply its own vlc libraries instead of the users having to manually install them
