### ISSUE TITLE
Crashes when playing any video by using a function (Arch Linux)

### ISSUE THREAD

**Issue by BeastlyGhost** [polybiusproxy/hxCodec#175]
to clarify: yes, i did set the function up properly (at least i hope i did), yes the file exists, yes I did try reinstalling VLC and other packages, and no, the in-game error handler does not return anything that could potentially help fix the issue

https://user-images.githubusercontent.com/45212377/181694030-592e75aa-02cc-45b2-acda-c438fa5bb19f.mp4

```Haxe
function startCutscene(name:String, library:String = 'assets')
{
	#if VIDEO_PLUGIN
	inCutscene = true;

	var path = Paths.video(name, library);
	#if sys
	if(!FileSystem.exists(path))
	#else
	if(!OpenFlAssets.exists(path))
	#end
	{
		FlxG.log.warn('Couldnt find video file: ' + name);
		startAndEnd();
		return;
	}
		
	var video:VideoHandler = new VideoHandler();
	video.playVideo(path);
	video.finishCallback = function()
	{
		startAndEnd();
		return;
	}
	#else
	FlxG.log.warn('Platform not supported!');
	startAndEnd();
	return;
	#end
}
```

**Comment by polybiusproxy** [comment]
Linux support is kinda hard for me to fix, since I don't have a Linux machine nor I have any experience with Linux.
Any help would be appreciated.

**Comment by BeastlyGhost** [comment]
I actually found somewhat of a bandaid fix??? so basically, on my source code, I copied and pasted the files for hxCodec inside me source folder, commented out the hxCodec library line on Project.xml, ran the game and actually got them running just fine, I'm currently trying to find why is that the case, but funnily enough, this used to not be an obligatory thing

**Comment by BeastlyGhost** [comment]
closing this for now
