### ISSUE TITLE
Saw you forgot to make a variable for oldTime.

### ISSUE THREAD

**Issue by TheRealJake12** [polybiusproxy/hxCodec#179]
![image](https://user-images.githubusercontent.com/84357907/185001476-64debce7-1f65-4930-bd7f-7b504c1bc929.png)
it happens to the best of us

**Comment by MAJigsaw77** [comment]
I made a pull request, I'm stupid sometimes

**Comment by ItsyourboyJonnycat** [comment]
there is also another error

**Comment by ItsyourboyJonnycat** [comment]
![Screen Shot 2022-08-16 at 8 55 44 PM](https://user-images.githubusercontent.com/107599365/185031510-29e84d64-3ebb-405b-b056-8e9db4c9c269.png)

**Comment by MAJigsaw77** [comment]
Fixed already

**Comment by MAJigsaw77** [comment]
In the pull request
