### ISSUE TITLE
video isnt visible latest commit

### ISSUE THREAD

**Issue by TheRealJake12** [polybiusproxy/hxCodec#181]
https://user-images.githubusercontent.com/84357907/185189011-6fb0a89d-50d4-4d39-a2e2-0f0da67bcdfb.mov

the audio plays but no video

**Comment by MAJigsaw77** [comment]
VideoHandler or VideoSprite?

**Comment by BoloVEVO** [comment]
It happens in both VideoHandler and VideoSprite.

**Comment by TheRealJake12** [comment]
Handler

**Comment by Raltyro** [comment]
this is also happening the same for me too
https://cdn.discordapp.com/attachments/929801502829215745/1009673607892447282/2022-08-18_10-57-43.mp4

**Comment by MAJigsaw77** [comment]
@Raltyro @BoloVEVO @TheRealJake12 
Try with the latest commit

**Comment by polybiusproxy** [comment]
Closing since the issue has been fixed, if it keeps happening, feel free to reopen it.
