### ISSUE TITLE
video disappears when resizing it

### ISSUE THREAD

**Issue by Sirox228** [polybiusproxy/hxCodec#188]
i need to resize video sprite, to make it smaller, but whenever i call setGraphicSize to videosprite or to videosprite.bitmap or to videohandler, video picture just disappears, i tried to graphic size it without updateHitbox(); result is the same.

**Comment by Sirox228** [comment]
![IMG_20220911_114834](https://user-images.githubusercontent.com/71220271/189519368-73c687a5-aab2-4e9a-a35a-2a6501eb4ca5.jpg)
this appears in logs when i use setGraphicSize

**Comment by polybiusproxy** [comment]
> ![IMG_20220911_114834](https://user-images.githubusercontent.com/71220271/189519368-73c687a5-aab2-4e9a-a35a-2a6501eb4ca5.jpg) this appears in logs when i use setGraphicSize (forgot to say, that all of that i'm doing on android)

Is that everything on the logs?

**Comment by Sirox228** [comment]
> Is that everything on the logs?
there's like 5 copies of the same log of File reading failed + Vlc could not open the file ..........system_fonts.xml (is on screenshot), but they're not changing anything, they are there even without setGraphicSize and video is working :/

**Comment by Sirox228** [comment]
> can you still hear the video? >
i just tested, audio is still there and working fine

**Comment by polybiusproxy** [comment]
> > can you still hear the video?
> 
> i just tested, audio is still there and working fine

You must also resize the video.
With the VideoSprite class, use `bitmap.set_width` and `bitmap.set_height`.

**Comment by Sirox228** [comment]
> > > can you still hear the video?
> > 
> > 
> > i just tested, audio is still there and working fine
> 
> You must also resize the video. With the VideoSprite class, use `bitmap.set_width` and `bitmap.set_height`.

i'll try it right now

**Comment by Sirox228** [comment]
@polybiusproxy it gives same 3 errors as in setGraphicSize, now, video not disappearing, but it didn't change it's size at all

**Comment by polybiusproxy** [comment]
> @polybiusproxy it gives same 3 errors as in setGraphicSize. now, video is not disappearing, but it didn't change it's width nor height at all

Can I get a picture of the problem?

**Comment by Sirox228** [comment]
> > @polybiusproxy it gives same 3 errors as in setGraphicSize. now, video is not disappearing, but it didn't change it's width nor height at all
> 
> Can I get a picture of the problem?

this is how it is now:
![Screenshot_2022-09-11-13-15-42-346_com coolpeople vshex](https://user-images.githubusercontent.com/71220271/189522367-b18dac18-c97a-4322-aa6a-1446a641a0eb.jpg)
that is how it should be:
![Screenshot_2022-09-11-13-13-23-706_com vanced android youtube](https://user-images.githubusercontent.com/71220271/189522378-5f5a4f03-9395-4559-92c3-41b582307456.jpg)
thats how i call it in code:
```haxe
var coolingVideo = new VideoSprite(-24, -224);
coolingVideo.bitmap.canSkip = false;
coolingVideo.playVideo(Paths.video('coolingVisualizer'), false, false);
//coolingVideo.setGraphicSize(945, 472);
coolingVideo.antialiasing = true;
coolingVideo.scrollFactor.set(0.9, 0.9);
coolingVideo.bitmap.set_width(150);
coolingVideo.bitmap.set_height(75);
coolingVideo.width = 150;
coolingVideo.height = 75;
//coolingVideo.updateHitbox();
add(coolingVideo);
```
whenever i call setGraphicSize that is now commented, i have those 3 errors with zoom, source AR and ViewPoint and video disappears, with bitmap.set_width etc. video not disappering, but those 3 errors are still there and video resolution is still the same as it was before i even tried to setGraphicSize it. if i remove graphic sizing and bitmap.set_width etc things, those 3 errors are gone, that means, that those are errors of resizing the video

**Comment by ItsyourboyJonnycat** [comment]
does the issue still occur?

**Comment by Sirox228** [comment]
@ItsyourboyJonnycat @polybiusproxy nothing changed after last commit, i added ``` coolingVideo.bitmap.canUseAutoResize = false; ``` but same log and same no resolution change when calling set_width and set_height (setGraphicSize kills videosprite like usual)

**Comment by polybiusproxy** [comment]
> @ItsyourboyJonnycat @polybiusproxy nothing changed after last commit, i added `coolingVideo.bitmap.canUseAutoResize = false;` but same log and same no resolution change when calling set_width and set_height (setGraphicSize kills videosprite like usual)

I don't really know how to fix this, so help would be required.

**Comment by Sirox228** [comment]
@polybiusproxy try to remove stage3d rendering and return old one, maybe it would work (in hex for windows, that uses old system, it somehow worked?)

**Comment by polybiusproxy** [comment]
> @polybiusproxy try to remove stage3d rendering and return old one, maybe it would work (in hex for windows, that uses old system, it somehow worked?)

Maybe a switch between Stage3D and BitmapData will do it...
Could you try to revert commit 46d5f3e on your local machine?

**Comment by Sirox228** [comment]
i don't know how to revert them, i'm stupid, can you say how?

**Comment by Sirox228** [comment]
i tried, result is the same

**Comment by JonnycatMeow** [comment]
is the same problem still occurring?

**Comment by Sirox228** [comment]
> is the problem still occurring?

no changes that can affect this were done, so no...

**Comment by JonnycatMeow** [comment]
well is fixed now?

**Comment by MAJigsaw77** [comment]
This issue got fixed rn

**Comment by MAJigsaw77** [comment]
You can simply use canvas Width or Height before the video to play then you can normally use width or height from FlxSprite.
