### ISSUE TITLE
hxCodec crashes in MacOS Ventura Beta

### ISSUE THREAD

**Issue by Raltyro** [polybiusproxy/hxCodec#192]
Self Explanatory
Last time tried with Psych Engine Lastest Git Build (with lastest git of hxCodec) with Crash Handler in it, Crashes without crash log

**Comment by polybiusproxy** [comment]
Might be an issue with the libraries.
I don't a macOS machine nor a Linux one so I can't test these types of issues. 🙁

Further help would be required.

**Comment by Eventretta** [comment]
i have a mac machine

**Comment by ItsyourboyJonnycat** [comment]
> Self Explanatory Last time tried with Psych Engine Lastest Git Build (with lastest git of hxCodec) with Crash Handler in it, Crashes without crash log

what error does it give you

**Comment by ItsyourboyJonnycat** [comment]
cause i have a mac

**Comment by ItsyourboyJonnycat** [comment]
![Screen Shot 2022-09-19 at 6 52 27 PM](https://user-images.githubusercontent.com/107599365/191149889-f628d93b-3257-45d1-9706-f679b8e148bf.png)
this is the version i have

**Comment by ItsyourboyJonnycat** [comment]
so i don't have the MacOS Ventura Beta

**Comment by ItsyourboyJonnycat** [comment]
and also i realized it crashes too so what i reccomend is going back to use the old v3 on xcode

**Comment by ItsyourboyJonnycat** [comment]
cause the v4 does not wanna work with xcode

**Comment by ItsyourboyJonnycat** [comment]
and here is the xcode releases

**Comment by ItsyourboyJonnycat** [comment]
i think the change fps thing may have caused the crash error

**Comment by ItsyourboyJonnycat** [comment]
@Raltyro does it still crash with the fix?

**Comment by Raltyro** [comment]
I havent tested it yet but have you test with your mac yet to see if it fixed for you?

**Comment by ItsyourboyJonnycat** [comment]
> I havent tested it yet but have you test with your mac yet to see if it fixed for you?

yeah it stills crashes

**Comment by ItsyourboyJonnycat** [comment]
@Raltyro does it still crash?

**Comment by ItsyourboyJonnycat** [comment]
ok doing further research i realized it is just the psych engine not the xcode or anything like that

**Comment by polybiusproxy** [comment]
As it appears to be an issue from Psych Engine, I'll close this issue.

**Comment by Raltyro** [comment]
> As it appears to be an issue from Psych Engine, I'll close this issue.

Hi there, came to check for the issue
i actually don't have a mac os, how do i know it crashes?
@Eventretta have one and told me in their view it seems like hxCodec crashes thru discord dms
meanwhile i check in my view it seems to work fine.

though i still doubt that this issue is from psych engine, and it might have something todo with native library for macOS
and there is still no responses from Eventretta yet about the crashes.

**Comment by Eventretta** [comment]
> > As it appears to be an issue from Psych Engine, I'll close this issue.
> 
> Hi there, came to check for the issue i actually don't have a mac os, how do i know it crashes? @Eventretta have one and told me in their view it seems like hxCodec crashes thru discord dms meanwhile i check in my view it seems to work fine.
> 
> though i still doubt that this issue is from psych engine, and it might have something todo with native library for macOS and there is still no responses from Eventretta yet about the crashes.

i dont have crashlogs, it just crashes
