### ISSUE TITLE
how do i add the mp4 as a background?

### ISSUE THREAD

**Issue by JonnycatMeow** [polybiusproxy/hxCodec#202]
hi im gonna do an fnf mod and i was wondering how you do it because i have seen kade do it for his mod so ye please help me!!!

**Comment by MemeHoovy** [comment]
although this doesn't use hxCodec, it has what your looking for though https://github.com/MijaeLio/animationVSfunkin-master

**Comment by polybiusproxy** [comment]
Hey - you can put your video on a FlxSprite and then blend it into the background.
It's that easy. 👍

**Comment by JonnycatMeow** [comment]
dang you guys should make a wiki for like that type of stuff

**Comment by Stilic** [comment]
use VideoSprite

**Comment by MAJigsaw77** [comment]
@JonnycatMeow close this
