### ISSUE TITLE
New Haxelib release when?

### ISSUE THREAD

**Issue by Stilic** [polybiusproxy/hxCodec#204]
@polybiusproxy I think the current Git version of the lib is stable enough to be released on Haxelib now.

**Comment by Raltyro** [comment]
I haven't think so, it looks like hxCodec for some Mac OS doesn't work and crashes for some reason
and the updating the video bitmapdata trick looks unstable

**Comment by JonnycatMeow** [comment]
i tested it in the macos monterey and it don't crash

**Comment by JonnycatMeow** [comment]
i think you whould need to use the hxcpp git version

**Comment by BushTrain460615** [comment]
> I haven't think so, it looks like hxCodec for some Mac OS doesn't work and crashes for some reason
> and the updating the video bitmapdata trick looks unstable

The MacOS version is a bit unstable considering it was only added a couple of pushes ago but it doesn't crash almost 70% of the time

**Comment by BushTrain460615** [comment]
but on macOS Ventura it runs good
