### ISSUE TITLE
Type not found: vlc.bitmap.VlcBitmap (Arch Linux)

### ISSUE THREAD

**Issue by InstantaneousRamen** [polybiusproxy/hxCodec#205]
I tried compiling the cancelled build of Hypno's Lullaby from FNF but everytime I try compiling it I get this error:
`
source/vlc/MP4Handler.hx:6: characters 8-28 : Type not found : vlc.bitmap.VlcBitmap`
`source/vlc/MP4Handler.hx:12: characters 26-35 : Type not found : VlcBitmap`
I have tried installing hxCodec from the git and using haxelib install hxCodec but nothing has worked, I even compiled VLC to see if I needed the package but it still doesn't seem to work.

**Comment by TheRealJake12** [comment]
its using the old version of HXCodec (before it was called that). You shouldn't have to use `vlc.bitmap.VlcBitmap` anymore

**Comment by InstantaneousRamen** [comment]
Yeah, but the problem is that I don't code in Haxe and pretty much all the time I just compile the source code as it is, so I don't know what to change at all to fix the error.
