### ISSUE TITLE
Is it normal that audio doesn't work?

### ISSUE THREAD

**Issue by TheGaloXx** [polybiusproxy/hxCodec#208]
The video has sound but not in the game.

**Comment by JonnycatMeow** [comment]
it is not normal please tell us what platform are you on and what does the terminal says

**Comment by TheGaloXx** [comment]
> 
I compile in Windows targeting Debug.
But never mind, I tried again a day later and it works now, I don't know what was the problem, but thank you anyways.

**Comment by JonnycatMeow** [comment]
no problem
