### ISSUE TITLE
is it possible it add a shader to a video? 

### ISSUE THREAD

**Issue by JonnycatMeow** [polybiusproxy/hxCodec#209]
when i mean shader i mean like haxe shaders being applied to a video?

**Comment by TheKitBoi** [comment]
https://user-images.githubusercontent.com/84044666/203924703-3e05369b-4f3a-4636-b8ef-09ef9ffc8f2d.mp4

you can in psych engine
if you want the script ask me

**Comment by JonnycatMeow** [comment]
yes can i have the script

**Comment by JonnycatMeow** [comment]
and can you please tell me the steps on how you did that.

**Comment by TheKitBoi** [comment]
> @TheKitBoi can you please tell me the steps on how you did that.
1.Put this videoSprite into a mods folder
[videoSprite.txt](https://github.com/polybiusproxy/hxCodec/files/10094419/videoSprite.txt) rename the .txt into .lua
2. find this line in the videoSprites.lua "var filepath = Paths.video('videoname');" rename videoname to a name from the video folder
3.you can put whatever shader you like in the shaders folder example
[gameboy.txt](https://github.com/polybiusproxy/hxCodec/files/10094410/gameboy.txt) rename the .txt into .frag
3.paste this line to a script your using in a function (onCreatePost) setSpriteShader("videoSprite", gameboy) you can change gameboy to a diffrent name
4.you can use this line in a script setObjectCamera("videoSprite", 'camhud');
5.add this line onSongStart() if you want it to start at a song addLuaScript('videoSprite')

**Comment by JonnycatMeow** [comment]
thank you and if there could also be a way to modifie it from source code? if you know a way please tell me so i can be able to add it @TheKitBoi

**Comment by MAJigsaw77** [comment]
@JonnycatMeow close this
