### ISSUE TITLE
is it possible to add support to html5?

### ISSUE THREAD

**Issue by JonnycatMeow** [polybiusproxy/hxCodec#211]
i know html5 is not really a good platform but could there be a way

**Comment by polybiusproxy** [comment]
Hi--HTML5 was supported, but support for it was removed (for some reason I forgot)

**Comment by JonnycatMeow** [comment]
i think its still supported https://wiki.videolan.org/Documentation:WebPlugin/ please look at this document

**Comment by JonnycatMeow** [comment]
the reason why it was dropped because of the NPAPI plugins were removed but some browsers still support it

**Comment by JonnycatMeow** [comment]
actually nvm it seem that you were right https://forum.videolan.org/viewtopic.php?t=146878

**Comment by MAJigsaw77** [comment]
@JonnycatMeow can you close this?

**Comment by JonnycatMeow** [comment]
yeah....
