### ISSUE TITLE
Video frames only changing when resizing/moving window

### ISSUE THREAD

**Issue by ai186** [polybiusproxy/hxCodec#217]
For some reason, playing videos just plays the audio and a frozen frame for me - unless I move or resize the window, then it updates to whatever frame it should be at, but then it freezes at that frame.

I don't get any outputs or errors from the terminal. I checked the time, and it is updating. The audio is normal. But for some reason the bitmap only updates when I mess with the window.

I am using the git version of hxCodec.

**Comment by ai186** [comment]
I've "fixed" it by putting this piece of code, but preferably it would be nice if it wasn't neccesary for me

```hx
        onPositionChanged = (x) -> {
            if (bitmapData != null)
            bitmapData.draw(bitmapData);
        }
```

**Comment by MAJigsaw77** [comment]
> For some reason, playing videos just plays the audio and a frozen frame for me - unless I move or resize the window, then it updates to whatever frame it should be at, but then it freezes at that frame.
> 
> I don't get any outputs or errors from the terminal. I checked the time, and it is updating. The audio is normal. But for some reason the bitmap only updates when I mess with the window.
> 
> I am using the git version of hxCodec.

Try to add this when the texture uploads the byte array
```
```

**Comment by MAJigsaw77** [comment]
Try this and tell what has been changed

**Comment by MAJigsaw77** [comment]
This should be closed, is fixed in the latest commit
