### ISSUE TITLE
can you add Jigsaw to your hxcodec respiratory please!!!

### ISSUE THREAD

**Issue by JonnycatMeow** [polybiusproxy/hxCodec#219]
he is a really good coder and he will be a really good edition to the hxcodec team!!! @polybiusproxy

**Comment by polybiusproxy** [comment]
@MAJigsaw77 What do you think?

**Comment by MAJigsaw77** [comment]
Idk, if you want to add me, is your choice.

**Comment by polybiusproxy** [comment]
> Idk, if you want to add me, is your choice.

Check your email.

**Comment by JonnycatMeow** [comment]
dang good job jigsaw
