### ISSUE TITLE
VideoSprite doesn't work

### ISSUE THREAD

**Issue by swordcube** [polybiusproxy/hxCodec#221]
This is what errors happen when i try to play a video on Arch Linux, Audio works fine.
![image](https://user-images.githubusercontent.com/49110074/210477752-421997bc-4b00-40f4-840f-be3bc11d9bae.png)

It crashes the game entirely on Windows with no errors, warnings, or logs.

I'm using the git version of hxCodec and NOT the haxelib version.

**Comment by MAJigsaw77** [comment]
Are you sure it crashes on windows? What type of video did you tryed to play?

**Comment by swordcube** [comment]
> Are you sure it crashes on windows? What type of video did you tryed to play?

mp4, and this still happens on your repo + this one

**Comment by swordcube** [comment]
After a whole lot of testing, It appears that VideoSprite is broken, VideoHandler now works fine.

**Comment by MAJigsaw77** [comment]
On ready it loads a graphic.

**Comment by swordcube** [comment]
that graphic being a black screen

> On ready it loads a graphic.

**Comment by MAJigsaw77** [comment]
Yeah 💀

**Comment by MAJigsaw77** [comment]
This issue got fixed

**Comment by swordcube** [comment]
i'm still having this issue though :sob:
