### ISSUE TITLE
The Library does not want to compile on Linux

### ISSUE THREAD

**Issue by teotm** [polybiusproxy/hxCodec#233]
My friend while compiling on Linux, encountered this issue and I do not know why this happens. They use a 2.6.1 version of the Haxelib.
```
Link: ApplicationMain
/usr/bin/ld:/home/USERNAME/Desktop/Repository-Path/.haxelib/hxCodec/2,6,1/lib/vlc/lib/Linux/libvlc.so.5: file format not recognized; treating as linker script
/usr/bin/ld:/home/USERNAME/Desktop/Repository-Path/.haxelib/hxCodec/2,6,1/lib/vlc/lib/Linux/libvlc.so.5:0: syntax error
collect2: error: ld returned 1 exit status
```
If there's anything more to say, just go ahead and ask

**Comment by MAJigsaw77** [comment]
Have you read the the instructions on the repo?

**Comment by teotm** [comment]
I even made a workflow file in my repo that compiles to Linux and added these three commands to it and I still get the same compiling error
![image](https://user-images.githubusercontent.com/84466597/214362422-a3f78f15-67cb-42a4-a1d9-2a943273b6e0.png)

**Comment by teotm** [comment]
Added them all to the workflow file still having the same problem.

**Comment by MAJigsaw77** [comment]
Try with the latest commit

**Comment by swordcube** [comment]
yeah i opened a pr for a fix and it got merged

**Comment by teotm** [comment]
okay lemme check it in a while

**Comment by teotm** [comment]
It's working now! Thanks a lot!
