### ISSUE TITLE
Setting Volume isn't working for me

### ISSUE THREAD

**Issue by KirbyKid256** [polybiusproxy/hxCodec#238]
I'm trying to set the volume of a video playing, but it's always at 100 or 0 if it can't use sound.
I don't know if this is an issue with hxCodec or if I'm missing something, but the volume isn't working.

**Comment by KirbyKid256** [comment]
So I checked the code, and it's definitally this line of code that's causing it:
`volume = Std.int(#if FLX_SOUND_SYSTEM ((FlxG.sound.muted || !canUseSound) ? 0 : 1) * #end FlxG.sound.volume * 100);`
You could add another volume multiplier to change the volume of a specific video where it would be a float.

**Comment by MAJigsaw77** [comment]
Can't use

**Comment by MAJigsaw77** [comment]
Can't use sound makes the video to not have sound at all duh
