### ISSUE TITLE
linux and actions builds

### ISSUE THREAD

**Issue by TheRealJake12** [polybiusproxy/hxCodec#239]
![image](https://user-images.githubusercontent.com/84357907/218329272-b1a0c675-0512-465e-98e8-2efec1260510.png)

using latest commit

**Comment by MAJigsaw77** [comment]
...
```bash
sudo apt-get install glibc-source
sudo apt-get install libidn12
sudo apt-get install libidn-dev
```

**Comment by swordcube** [comment]
and just in case,
```
sudo apt-get install vlc
```

because vlc might not be installed

**Comment by TheRealJake12** [comment]
thanks, I have no idea if the videos work but it compiles. Thanks bros
