### ISSUE TITLE
an incomprehensible error

### ISSUE THREAD

**Issue by Delmik1** [polybiusproxy/hxCodec#259]
> Error: haxelib: hxCodec
,]D hxCodec=2.6.1axe\lib\hxCodec/2,6,1/dec/2,6,1/ndll/

When I tried to compile, the following error occurred. I didn't fix anything in the library and I just called up FlxVideooSprite and I got this error. I can't even figure out the cause.

**Comment by MAJigsaw77** [comment]
What libs do you use? what versions do they have? what platform did you tried to compile?

**Comment by Delmik1** [comment]
only hxCodec, and 4.3.0. compile target is window.

I am currently figuring out the cause. Then I realized that haxe was updated, so I'm installing haxe 4.3.1.

**Comment by Delmik1** [comment]
And I just confirmed that the same error occurs regardless of the version of haxe.

**Comment by MAJigsaw77** [comment]
Haxe doesn't have anything to do with it, try the latest commit I made rn

**Comment by Delmik1** [comment]
The same error occurred. There is no change.

**Comment by Delmik1** [comment]
However, I learned one thing: adding the hxCodec library to project.xml itself does not cause errors. However, an error occurs as soon as you import and use VideoSprite or VideoHandler.

**Comment by MAJigsaw77** [comment]
> The same error occurred. There is no change.

Tryna remove the library then git it back

**Comment by Delmik1** [comment]
I even confirmed that hxcpp made an error that the hxcpp could not find the hxcodec library by attempting to compile it after removing it with certainty through the command 'haxelib remove hxCodec'.

After that, I installed hxCodec from git again and tried to recompile it, but I still got the same error.

And in the meantime, I've tried turning the laptop off and on several times, but there's no significant change.

And this is my hardware information. I'm leaving this in the hope that this will help you.

ROG Strix G512LU_G512U (Laptop)
Windows 11 Pro 22H2

**Comment by MAJigsaw77** [comment]
You are trying to compile android or?

**Comment by MAJigsaw77** [comment]
> You are trying to compile android or?

If yes, you should probably update lime and openfl to the latest version cause I tested this commit and it compiled without any issues

**Comment by Delmik1** [comment]
i tried compile only windows.

and i got same error after updated every libraries to latest version.

> flixel: 5.2.1 5.2.2 [5.3.0]
> haxelib: [4.0.3]
> hxcpp: 4.2.1 [4.3.2]
> lime: 8.0.0 [8.0.1]
> openfl: 9.2.0 [9.2.1]

**Comment by MAJigsaw77** [comment]
windows doesn't have anything to do with ndll folder .___.
