### ISSUE TITLE
fix the html5 and android x86_64 issue

### ISSUE THREAD

**Issue by mcagabe19** [polybiusproxy/hxCodec#260]
Error:
``C:/Users/mcagabe19/Github/haxelib/hxCodec/git/hxcodec/vlc/LibVLC.hx:173: characters 55-90 : You cannot access the cpp package while targeting js (for cpp.RawConstPointer)``

and a question its supports html5?

also error in android x86_64 after im started use latest hxCodec:
``Process creation failure : clang++``

**Comment by MAJigsaw77** [comment]
Dude, hxCodec works only on c++ target

**Comment by mcagabe19** [comment]
> Dude, hxCodec works only on c++ target

fair lmao
