### ISSUE TITLE
android fatal error

### ISSUE THREAD

**Issue by mcagabe19** [polybiusproxy/hxCodec#266]
hi after updating hxCodec to git (latest) it giving me a fatal error at PlayState

--------- beginning of crash
``05-04 17:49:11.098 19146 19171 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x5c000005 in tid 19171 (SDLThread), pid 19146 (SDLActivity)``

i used logcat to get too
[here](https://www.mediafire.com/file/tq5bkh6xqlrf3hn/archive2.zip/file) is full log and tombstone
i think after updating the libVLC did it

**Comment by MAJigsaw77** [comment]
I haven't had any issues with the new libs, tell in what way did you used hxCodec

**Comment by MAJigsaw77** [comment]
-______-

**Comment by mcagabe19** [comment]
then ok still stuck in 2.5.1 perfect...

**Comment by MAJigsaw77** [comment]
Your logs doesn't point anything about libvlc or hxCodec so it's definitely another issue

**Comment by MAJigsaw77** [comment]
Try to use hxCodec in another context than playstate

**Comment by MAJigsaw77** [comment]
That's all
