### ISSUE TITLE
libvlc.lib fatal error

### ISSUE THREAD

**Issue by TheRealJake12** [polybiusproxy/hxCodec#275]
![image](https://github.com/polybiusproxy/hxCodec/assets/84357907/af8051ac-1998-4e7a-8561-df9bcac038a2)
cannot compile using the latest hxCodec release

**Comment by MAJigsaw77** [comment]
Specify the stuff you use with they're versions

**Comment by TheRealJake12** [comment]
> Specify the stuff you use with they're versions

using the develop branch fixes the problem

**Comment by MAJigsaw77** [comment]
> > Specify the stuff you use with they're versions
> 
> using the develop branch fixes the problem

🤨 What

**Comment by MAJigsaw77** [comment]
It does have chnages to Build.xml that might affect windows

**Comment by TheRealJake12** [comment]
like, do you need all my library versions?

**Comment by MAJigsaw77** [comment]
> like, do you need all my library versions?

lime, haxe, hxcpp

**Comment by MAJigsaw77** [comment]
But look on discord for a bit
