### ISSUE TITLE
3.0.1 not working with macOS Ventura 13.3.1

### ISSUE THREAD

**Issue by TheWorldMachinima** [polybiusproxy/hxCodec#279]
I installed hxCodec 3.0.1 to my Mac today but I keep getting tons of error at the end of compiling.
2.6.1 worked fine, no luck in 3.0.1.

Errors:
```bash
Undefined symbols for architecture x86_64:
  "_libvlc_audio_get_channel", referenced from:
      hxcodec::openfl::Video_obj::get_channel() in fe7c07a1_Video.o
  "_libvlc_audio_get_delay", referenced from:
      hxcodec::openfl::Video_obj::get_delay() in fe7c07a1_Video.o
  "_libvlc_audio_get_mute", referenced from:
      hxcodec::openfl::Video_obj::get_mute() in fe7c07a1_Video.o
  "_libvlc_audio_get_volume", referenced from:
      hxcodec::openfl::Video_obj::get_volume() in fe7c07a1_Video.o
  "_libvlc_audio_set_channel", referenced from:
      hxcodec::openfl::Video_obj::set_channel(int) in fe7c07a1_Video.o
  "_libvlc_audio_set_delay", referenced from:
      hxcodec::openfl::Video_obj::set_delay(int) in fe7c07a1_Video.o
  "_libvlc_audio_set_mute", referenced from:
      hxcodec::openfl::Video_obj::set_mute(bool) in fe7c07a1_Video.o
  "_libvlc_audio_set_volume", referenced from:
      hxcodec::openfl::Video_obj::set_volume(int) in fe7c07a1_Video.o
  "_libvlc_event_attach", referenced from:
      hxcodec::openfl::Video_obj::attachEvents() in fe7c07a1_Video.o
  "_libvlc_event_detach", referenced from:
      hxcodec::openfl::Video_obj::detachEvents() in fe7c07a1_Video.o
  "_libvlc_media_add_option", referenced from:
      hxcodec::openfl::Video_obj::play(String, hx::Null<bool>) in fe7c07a1_Video.o
  "_libvlc_media_get_duration", referenced from:
      hxcodec::openfl::Video_obj::get_duration() in fe7c07a1_Video.o
  "_libvlc_media_get_mrl", referenced from:
      hxcodec::openfl::Video_obj::get_mrl() in fe7c07a1_Video.o
  "_libvlc_media_new_location", referenced from:
      hxcodec::openfl::Video_obj::play(String, hx::Null<bool>) in fe7c07a1_Video.o
  "_libvlc_media_new_path", referenced from:
      hxcodec::openfl::Video_obj::play(String, hx::Null<bool>) in fe7c07a1_Video.o
  "_libvlc_media_player_can_pause", referenced from:
      hxcodec::openfl::Video_obj::get_canPause() in fe7c07a1_Video.o
  "_libvlc_media_player_event_manager", referenced from:
      hxcodec::openfl::Video_obj::attachEvents() in fe7c07a1_Video.o
  "_libvlc_media_player_get_length", referenced from:
      hxcodec::openfl::Video_obj::get_length() in fe7c07a1_Video.o
  "_libvlc_media_player_get_position", referenced from:
      hxcodec::openfl::Video_obj::get_position() in fe7c07a1_Video.o
  "_libvlc_media_player_get_rate", referenced from:
      hxcodec::openfl::Video_obj::get_rate() in fe7c07a1_Video.o
  "_libvlc_media_player_get_time", referenced from:
      hxcodec::openfl::Video_obj::get_time() in fe7c07a1_Video.o
  "_libvlc_media_player_is_playing", referenced from:
      hxcodec::openfl::Video_obj::get_isPlaying() in fe7c07a1_Video.o
  "_libvlc_media_player_is_seekable", referenced from:
      hxcodec::openfl::Video_obj::get_isSeekable() in fe7c07a1_Video.o
  "_libvlc_media_player_new_from_media", referenced from:
      hxcodec::openfl::Video_obj::play(String, hx::Null<bool>) in fe7c07a1_Video.o
  "_libvlc_media_player_pause", referenced from:
      hxcodec::openfl::Video_obj::togglePaused() in fe7c07a1_Video.o
  "_libvlc_media_player_play", referenced from:
      hxcodec::openfl::Video_obj::play(String, hx::Null<bool>) in fe7c07a1_Video.o
  "_libvlc_media_player_release", referenced from:
      hxcodec::openfl::Video_obj::dispose() in fe7c07a1_Video.o
  "_libvlc_media_player_set_media", referenced from:
      hxcodec::openfl::Video_obj::play(String, hx::Null<bool>) in fe7c07a1_Video.o
  "_libvlc_media_player_set_pause", referenced from:
      hxcodec::openfl::Video_obj::pause() in fe7c07a1_Video.o
      hxcodec::openfl::Video_obj::resume() in fe7c07a1_Video.o
  "_libvlc_media_player_set_position", referenced from:
      hxcodec::openfl::Video_obj::set_position(float) in fe7c07a1_Video.o
  "_libvlc_media_player_set_rate", referenced from:
      hxcodec::openfl::Video_obj::set_rate(float) in fe7c07a1_Video.o
  "_libvlc_media_player_set_time", referenced from:
      hxcodec::openfl::Video_obj::set_time(int) in fe7c07a1_Video.o
  "_libvlc_media_player_stop", referenced from:
      hxcodec::openfl::Video_obj::stop() in fe7c07a1_Video.o
      hxcodec::openfl::Video_obj::dispose() in fe7c07a1_Video.o
  "_libvlc_media_release", referenced from:
      hxcodec::openfl::Video_obj::play(String, hx::Null<bool>) in fe7c07a1_Video.o
  "_libvlc_new", referenced from:
      hxcodec::openfl::Video_obj::__construct() in fe7c07a1_Video.o
  "_libvlc_release", referenced from:
      hxcodec::openfl::Video_obj::dispose() in fe7c07a1_Video.o
  "_libvlc_video_set_callbacks", referenced from:
      hxcodec::openfl::Video_obj::play(String, hx::Null<bool>) in fe7c07a1_Video.o
  "_libvlc_video_set_format_callbacks", referenced from:
      hxcodec::openfl::Video_obj::play(String, hx::Null<bool>) in fe7c07a1_Video.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by MAJigsaw77** [comment]
> I installed hxCodec 3.0.1 to my Mac today but I keep getting tons of error at the end of compiling. 2.6.1 worked fine, no luck in 3.0.1.
> 
> Errors:
> 
> ```shell
> Undefined symbols for architecture x86_64:
>   "_libvlc_audio_get_channel", referenced from:
>       hxcodec::openfl::Video_obj::get_channel() in fe7c07a1_Video.o
>   "_libvlc_audio_get_delay", referenced from:
>       hxcodec::openfl::Video_obj::get_delay() in fe7c07a1_Video.o
>   "_libvlc_audio_get_mute", referenced from:
>       hxcodec::openfl::Video_obj::get_mute() in fe7c07a1_Video.o
>   "_libvlc_audio_get_volume", referenced from:
>       hxcodec::openfl::Video_obj::get_volume() in fe7c07a1_Video.o
>   "_libvlc_audio_set_channel", referenced from:
>       hxcodec::openfl::Video_obj::set_channel(int) in fe7c07a1_Video.o
>   "_libvlc_audio_set_delay", referenced from:
>       hxcodec::openfl::Video_obj::set_delay(int) in fe7c07a1_Video.o
>   "_libvlc_audio_set_mute", referenced from:
>       hxcodec::openfl::Video_obj::set_mute(bool) in fe7c07a1_Video.o
>   "_libvlc_audio_set_volume", referenced from:
>       hxcodec::openfl::Video_obj::set_volume(int) in fe7c07a1_Video.o
>   "_libvlc_event_attach", referenced from:
>       hxcodec::openfl::Video_obj::attachEvents() in fe7c07a1_Video.o
>   "_libvlc_event_detach", referenced from:
>       hxcodec::openfl::Video_obj::detachEvents() in fe7c07a1_Video.o
>   "_libvlc_media_add_option", referenced from:
>       hxcodec::openfl::Video_obj::play(String, hx::Null<bool>) in fe7c07a1_Video.o
>   "_libvlc_media_get_duration", referenced from:
>       hxcodec::openfl::Video_obj::get_duration() in fe7c07a1_Video.o
>   "_libvlc_media_get_mrl", referenced from:
>       hxcodec::openfl::Video_obj::get_mrl() in fe7c07a1_Video.o
>   "_libvlc_media_new_location", referenced from:
>       hxcodec::openfl::Video_obj::play(String, hx::Null<bool>) in fe7c07a1_Video.o
>   "_libvlc_media_new_path", referenced from:
>       hxcodec::openfl::Video_obj::play(String, hx::Null<bool>) in fe7c07a1_Video.o
>   "_libvlc_media_player_can_pause", referenced from:
>       hxcodec::openfl::Video_obj::get_canPause() in fe7c07a1_Video.o
>   "_libvlc_media_player_event_manager", referenced from:
>       hxcodec::openfl::Video_obj::attachEvents() in fe7c07a1_Video.o
>   "_libvlc_media_player_get_length", referenced from:
>       hxcodec::openfl::Video_obj::get_length() in fe7c07a1_Video.o
>   "_libvlc_media_player_get_position", referenced from:
>       hxcodec::openfl::Video_obj::get_position() in fe7c07a1_Video.o
>   "_libvlc_media_player_get_rate", referenced from:
>       hxcodec::openfl::Video_obj::get_rate() in fe7c07a1_Video.o
>   "_libvlc_media_player_get_time", referenced from:
>       hxcodec::openfl::Video_obj::get_time() in fe7c07a1_Video.o
>   "_libvlc_media_player_is_playing", referenced from:
>       hxcodec::openfl::Video_obj::get_isPlaying() in fe7c07a1_Video.o
>   "_libvlc_media_player_is_seekable", referenced from:
>       hxcodec::openfl::Video_obj::get_isSeekable() in fe7c07a1_Video.o
>   "_libvlc_media_player_new_from_media", referenced from:
>       hxcodec::openfl::Video_obj::play(String, hx::Null<bool>) in fe7c07a1_Video.o
>   "_libvlc_media_player_pause", referenced from:
>       hxcodec::openfl::Video_obj::togglePaused() in fe7c07a1_Video.o
>   "_libvlc_media_player_play", referenced from:
>       hxcodec::openfl::Video_obj::play(String, hx::Null<bool>) in fe7c07a1_Video.o
>   "_libvlc_media_player_release", referenced from:
>       hxcodec::openfl::Video_obj::dispose() in fe7c07a1_Video.o
>   "_libvlc_media_player_set_media", referenced from:
>       hxcodec::openfl::Video_obj::play(String, hx::Null<bool>) in fe7c07a1_Video.o
>   "_libvlc_media_player_set_pause", referenced from:
>       hxcodec::openfl::Video_obj::pause() in fe7c07a1_Video.o
>       hxcodec::openfl::Video_obj::resume() in fe7c07a1_Video.o
>   "_libvlc_media_player_set_position", referenced from:
>       hxcodec::openfl::Video_obj::set_position(float) in fe7c07a1_Video.o
>   "_libvlc_media_player_set_rate", referenced from:
>       hxcodec::openfl::Video_obj::set_rate(float) in fe7c07a1_Video.o
>   "_libvlc_media_player_set_time", referenced from:
>       hxcodec::openfl::Video_obj::set_time(int) in fe7c07a1_Video.o
>   "_libvlc_media_player_stop", referenced from:
>       hxcodec::openfl::Video_obj::stop() in fe7c07a1_Video.o
>       hxcodec::openfl::Video_obj::dispose() in fe7c07a1_Video.o
>   "_libvlc_media_release", referenced from:
>       hxcodec::openfl::Video_obj::play(String, hx::Null<bool>) in fe7c07a1_Video.o
>   "_libvlc_new", referenced from:
>       hxcodec::openfl::Video_obj::__construct() in fe7c07a1_Video.o
>   "_libvlc_release", referenced from:
>       hxcodec::openfl::Video_obj::dispose() in fe7c07a1_Video.o
>   "_libvlc_video_set_callbacks", referenced from:
>       hxcodec::openfl::Video_obj::play(String, hx::Null<bool>) in fe7c07a1_Video.o
>   "_libvlc_video_set_format_callbacks", referenced from:
>       hxcodec::openfl::Video_obj::play(String, hx::Null<bool>) in fe7c07a1_Video.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ```

3.0.1 doesn't have mac support, this next patch will have it, but if you want it earlier, just git the main branch...
