### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by TheoDevelops** [polybiusproxy/hxCodec#281]
Hi, im coding in haxeflixel, i made this

```haxe
public function startVideo(name:String)
{
      FlxG.sound.music.stop();

      camStage.alpha = 0;
      camObjects.alpha = 0;

      var video:FlxVideo = new FlxVideo();
      video.onEndReached.add(video.dispose);
      video.onEndReached.add(onVideoEnd);
      video.play(Asset.video(name));
}
public function onVideoEnd():Void
{
      camStage.alpha = 1;
      camObjects.alpha = 1;

      FlxG.sound.playMusic(Asset.music('mainMenu'), 1);
}
```

and i get this in the console
[0000023e406da3c0] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[0000023e4eddcbb0] main vout display error: Failed to set on top
[0000023e4ec24200] main vout display error: Failed to set on top

is my first time using this lib, i imported the lib
also it sound, but does not show the video, just the audio

(also is not the alpha of cameras)

can some one help?

**Comment by MAJigsaw77** [comment]
Update to 3.0.2 as the previous had a little issue

**Comment by TheoDevelops** [comment]
also i updated and same
[000001d001339420] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001d028c92f80] main vout display error: Failed to set on top
[000001d028cb17c0] main vout display error: Failed to set on top

**Comment by TheoDevelops** [comment]
> Update to 3.0.2 as the previous had a little issue

[000001d001339420] mmdevice audio output error: cannot initialize COM (error 0x80010106)
source/MusicBeatState.hx:57: reg (x: -200 | y: -200 | w: 1792 | h: 1008)
[000001d028c92f80] main vout display error: Failed to set on top
[000001d028cb17c0] main vout display error: Failed to set on top

**Comment by TheoDevelops** [comment]
> Update to 3.0.2 as the previous had a little issue

also im updated it and
[000001d001339420] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001d028c92f80] main vout display error: Failed to set on top
[000001d028cb17c0] main vout display error: Failed to set on top

**Comment by polybiusproxy** [comment]
> > Update to 3.0.2 as the previous had a little issue
> 
> also im updated it and [000001d001339420] mmdevice audio output error: cannot initialize COM (error 0x80010106) [000001d028c92f80] main vout display error: Failed to set on top [000001d028cb17c0] main vout display error: Failed to set on top
> 
> same error
> 
> im using 3.0.2, also, audio starts but, doesnt show the video and, onEndReached doesnt work

Hello,

What platform are you in?
You may be missing some plugins. Are you sure you're importing the library correctly?

**Comment by TheoDevelops** [comment]
> > > Update to 3.0.2 as the previous had a little issue
> > 
> > 
> > also im updated it and [000001d001339420] mmdevice audio output error: cannot initialize COM (error 0x80010106) [000001d028c92f80] main vout display error: Failed to set on top [000001d028cb17c0] main vout display error: Failed to set on top
> > same error
> > im using 3.0.2, also, audio starts but, doesnt show the video and, onEndReached doesnt work
> 
> Hello,
> 
> What platform are you in? You may be missing some plugins. Are you sure you're importing the library correctly?

im in windows 10, and, yes, i think, im only installed hxcodec and, im imported it from hxcodec.flixel.FlxVideo

**Comment by polybiusproxy** [comment]
Do you have a `plugins` folder on the same folder as your executable's?

**Comment by TheoDevelops** [comment]
> Do you have a `plugins` folder on the same folder as your executable's?

yep, in plugins folder contains
- 10/08/2023  10:13 a. m.    <DIR>          access
10/08/2023  10:13 a. m.    <DIR>          access_output
10/08/2023  10:13 a. m.    <DIR>          audio_filter
10/08/2023  10:13 a. m.    <DIR>          audio_mixer
10/08/2023  10:13 a. m.    <DIR>          audio_output
10/08/2023  10:13 a. m.    <DIR>          codec
10/08/2023  10:13 a. m.    <DIR>          control
10/08/2023  10:13 a. m.    <DIR>          d3d11
10/08/2023  10:13 a. m.    <DIR>          d3d9
10/08/2023  10:13 a. m.    <DIR>          demux
10/08/2023  10:13 a. m.    <DIR>          gui
10/08/2023  10:13 a. m.    <DIR>          keystore
10/08/2023  10:13 a. m.    <DIR>          logger
10/08/2023  10:13 a. m.    <DIR>          lua
10/08/2023  10:13 a. m.    <DIR>          meta_engine
10/08/2023  10:13 a. m.    <DIR>          misc
10/08/2023  10:13 a. m.    <DIR>          mux
10/08/2023  10:13 a. m.    <DIR>          packetizer
10/08/2023  10:55 a. m.           314,893 plugins.dat
10/08/2023  10:13 a. m.    <DIR>          services_discovery
10/08/2023  10:13 a. m.    <DIR>          spu
10/08/2023  10:13 a. m.    <DIR>          stream_extractor
10/08/2023  10:13 a. m.    <DIR>          stream_filter
10/08/2023  10:13 a. m.    <DIR>          stream_out
10/08/2023  10:13 a. m.    <DIR>          text_renderer
10/08/2023  10:13 a. m.    <DIR>          video_chroma
10/08/2023  10:13 a. m.    <DIR>          video_filter
10/08/2023  10:13 a. m.    <DIR>          video_output
10/08/2023  10:13 a. m.    <DIR>          video_splitter
10/08/2023  10:13 a. m.    <DIR>          visualization

**Comment by polybiusproxy** [comment]
I'm not sure about the cause of the issue. Try deleting hxCodec from your PC, then reinstall the library. If that doesn't work, I don't know what could fix it.
