### ISSUE TITLE
unresolved external symbole

### ISSUE THREAD

**Issue by Karim-Akra** [polybiusproxy/hxCodec#282]
i've been using hxCodec for a while. mostly since 2.5.

when 2.6.1 was released it was working fine but suddenly after few weeks i was getting a error message while compiling to windows or android

i updated to latest(3.0.1) which fixed the issue but yet again i got the same error message. downgrading didn't fix it and im not that good in libs so im very confused. im using this with psych engine 0.5.2H

error message: Link: ApplicationMain.exe
   Creating library ApplicationMain.lib and object ApplicationMain.exp
fe7c07a1_Video.obj : error LNK2019: unresolved external symbol _libvlc_new referenced in function "public: void __thiscall hxcodec::openfl::Video_obj::__construct(void)" (?__construct@Video_obj@openfl@hxcodec@@QAEXXZ)
fe7c07a1_Video.obj : error LNK2019: unresolved external symbol _libvlc_release referenced in function "public: virtual void __thiscall hxcodec::openfl::Video_obj::dispose(void)" (?dispose@Video_obj@openfl@hxcodec@@UAEXXZ)
fe7c07a1_Video.obj : error LNK2019: unresolved external symbol _libvlc_event_attach referenced in function "public: void __thiscall hxcodec::openfl::Video_obj::attachEvents(void)" (?attachEvents@Video_obj@openfl@hxcodec@@QAEXXZ)
fe7c07a1_Video.obj : error LNK2019: unresolved external symbol _libvlc_event_detach referenced in function "public: void __thiscall hxcodec::openfl::Video_obj::detachEvents(void)" (?detachEvents@Video_obj@openfl@hxcodec@@QAEXXZ)
fe7c07a1_Video.obj : error LNK2019: unresolved external symbol _libvlc_media_new_location referenced in function "public: virtual int __thiscall hxcodec::openfl::Video_obj::play(class String,struct hx::Null<bool>)" (?play@Video_obj@openfl@hxcodec@@UAEHVString@@U?$Null@_N@hx@@@Z)
fe7c07a1_Video.obj : error LNK2019: unresolved external symbol _libvlc_media_new_path referenced in function "public: virtual int __thiscall hxcodec::openfl::Video_obj::play(class String,struct hx::Null<bool>)" (?play@Video_obj@openfl@hxcodec@@UAEHVString@@U?$Null@_N@hx@@@Z)
fe7c07a1_Video.obj : error LNK2019: unresolved external symbol _libvlc_media_add_option referenced in function "public: virtual int __thiscall hxcodec::openfl::Video_obj::play(class String,struct hx::Null<bool>)" (?play@Video_obj@openfl@hxcodec@@UAEHVString@@U?$Null@_N@hx@@@Z)
fe7c07a1_Video.obj : error LNK2019: unresolved external symbol _libvlc_media_release referenced in function "public: virtual int __thiscall hxcodec::openfl::Video_obj::play(class String,struct hx::Null<bool>)" (?play@Video_obj@openfl@hxcodec@@UAEHVString@@U?$Null@_N@hx@@@Z)
fe7c07a1_Video.obj : error LNK2019: unresolved external symbol _libvlc_media_get_mrl referenced in function "public: class String __thiscall hxcodec::openfl::Video_obj::get_mrl(void)" (?get_mrl@Video_obj@openfl@hxcodec@@QAE?AVString@@XZ)
fe7c07a1_Video.obj : error LNK2019: unresolved external symbol _libvlc_media_get_duration referenced in function "public: int __thiscall hxcodec::openfl::Video_obj::get_duration(void)" (?get_duration@Video_obj@openfl@hxcodec@@QAEHXZ)
fe7c07a1_Video.obj : error LNK2019: unresolved external symbol _libvlc_media_player_new_from_media referenced in function "public: virtual int __thiscall hxcodec::openfl::Video_obj::play(class String,struct hx::Null<bool>)" (?play@Video_obj@openfl@hxcodec@@UAEHVString@@U?$Null@_N@hx@@@Z)
fe7c07a1_Video.obj : error LNK2019: unresolved external symbol _libvlc_media_player_release referenced in function "public: virtual void __thiscall hxcodec::openfl::Video_obj::dispose(void)" (?dispose@Video_obj@openfl@hxcodec@@UAEXXZ)
fe7c07a1_Video.obj : error LNK2019: unresolved external symbol _libvlc_media_player_set_media referenced in function "public: virtual int __thiscall hxcodec::openfl::Video_obj::play(class String,struct hx::Null<bool>)" (?play@Video_obj@openfl@hxcodec@@UAEHVString@@U?$Null@_N@hx@@@Z)
fe7c07a1_Video.obj : error LNK2019: unresolved external symbol _libvlc_media_player_event_manager referenced in function "public: void __thiscall hxcodec::openfl::Video_obj::attachEvents(void)" (?attachEvents@Video_obj@openfl@hxcodec@@QAEXXZ)
fe7c07a1_Video.obj : error LNK2019: unresolved external symbol _libvlc_media_player_is_playing referenced in function "public: bool __thiscall hxcodec::openfl::Video_obj::get_isPlaying(void)" (?get_isPlaying@Video_obj@openfl@hxcodec@@QAE_NXZ)
fe7c07a1_Video.obj : error LNK2019: unresolved external symbol _libvlc_media_player_play referenced in function "public: virtual int __thiscall hxcodec::openfl::Video_obj::play(class String,struct hx::Null<bool>)" (?play@Video_obj@openfl@hxcodec@@UAEHVString@@U?$Null@_N@hx@@@Z)
fe7c07a1_Video.obj : error LNK2019: unresolved external symbol _libvlc_media_player_set_pause referenced in function "class Dynamic __cdecl hxcodec::openfl::__Video_objpause(class hx::Object *)" (?__Video_objpause@openfl@hxcodec@@YA?AVDynamic@@PAVObject@hx@@@Z)
fe7c07a1_Video.obj : error LNK2019: unresolved external symbol _libvlc_media_player_pause referenced in function "class Dynamic __cdecl 
hxcodec::openfl::__Video_objtogglePaused(class hx::Object *)" (?__Video_objtogglePaused@openfl@hxcodec@@YA?AVDynamic@@PAVObject@hx@@@Z)
fe7c07a1_Video.obj : error LNK2019: unresolved external symbol _libvlc_media_player_stop referenced in function "class Dynamic __cdecl hxcodec::openfl::__Video_objstop(class hx::Object *)" (?__Video_objstop@openfl@hxcodec@@YA?AVDynamic@@PAVObject@hx@@@Z)
fe7c07a1_Video.obj : error LNK2019: unresolved external symbol _libvlc_video_set_callbacks referenced in function "public: virtual int __thiscall hxcodec::openfl::Video_obj::play(class String,struct hx::Null<bool>)" (?play@Video_obj@openfl@hxcodec@@UAEHVString@@U?$Null@_N@hx@@@Z)
fe7c07a1_Video.obj : error LNK2019: unresolved external symbol _libvlc_video_set_format_callbacks referenced in function "public: virtual int __thiscall hxcodec::openfl::Video_obj::play(class String,struct hx::Null<bool>)" (?play@Video_obj@openfl@hxcodec@@UAEHVString@@U?$Null@_N@hx@@@Z)
fe7c07a1_Video.obj : error LNK2019: unresolved external symbol _libvlc_media_player_get_length referenced in function "public: int __thiscall hxcodec::openfl::Video_obj::get_length(void)" (?get_length@Video_obj@openfl@hxcodec@@QAEHXZ)
fe7c07a1_Video.obj : error LNK2019: unresolved external symbol _libvlc_media_player_get_time referenced in function "public: int __thiscall hxcodec::openfl::Video_obj::get_time(void)" (?get_time@Video_obj@openfl@hxcodec@@QAEHXZ)
fe7c07a1_Video.obj : error LNK2019: unresolved external symbol _libvlc_media_player_set_time referenced in function "public: int __thiscall hxcodec::openfl::Video_obj::set_time(int)" (?set_time@Video_obj@openfl@hxcodec@@QAEHH@Z)
fe7c07a1_Video.obj : error LNK2019: unresolved external symbol _libvlc_media_player_get_position referenced in function "public: float __thiscall hxcodec::openfl::Video_obj::get_position(void)" (?get_position@Video_obj@openfl@hxcodec@@QAEMXZ)
fe7c07a1_Video.obj : error LNK2019: unresolved external symbol _libvlc_media_player_set_position referenced in function "public: float __thiscall hxcodec::openfl::Video_obj::set_position(float)" (?set_position@Video_obj@openfl@hxcodec@@QAEMM@Z)
fe7c07a1_Video.obj : error LNK2019: unresolved external symbol _libvlc_media_player_get_rate referenced in function "public: float __thiscall hxcodec::openfl::Video_obj::get_rate(void)" (?get_rate@Video_obj@openfl@hxcodec@@QAEMXZ)
fe7c07a1_Video.obj : error LNK2019: unresolved external symbol _libvlc_media_player_set_rate referenced in function "public: float __thiscall hxcodec::openfl::Video_obj::set_rate(float)" (?set_rate@Video_obj@openfl@hxcodec@@QAEMM@Z)
fe7c07a1_Video.obj : error LNK2019: unresolved external symbol _libvlc_media_player_is_seekable referenced in function "public: bool __thiscall hxcodec::openfl::Video_obj::get_isSeekable(void)" (?get_isSeekable@Video_obj@openfl@hxcodec@@QAE_NXZ)
fe7c07a1_Video.obj : error LNK2019: unresolved external symbol _libvlc_media_player_can_pause referenced in function "public: bool __thiscall hxcodec::openfl::Video_obj::get_canPause(void)" (?get_canPause@Video_obj@openfl@hxcodec@@QAE_NXZ)
fe7c07a1_Video.obj : error LNK2019: unresolved external symbol _libvlc_audio_get_mute referenced in function "public: bool __thiscall hxcodec::openfl::Video_obj::get_mute(void)" (?get_mute@Video_obj@openfl@hxcodec@@QAE_NXZ)
fe7c07a1_Video.obj : error LNK2019: unresolved external symbol _libvlc_audio_set_mute referenced in function "public: bool __thiscall hxcodec::openfl::Video_obj::set_mute(bool)" (?set_mute@Video_obj@openfl@hxcodec@@QAE_N_N@Z)
fe7c07a1_Video.obj : error LNK2019: unresolved external symbol _libvlc_audio_get_volume referenced in function "public: int __thiscall hxcodec::openfl::Video_obj::get_volume(void)" (?get_volume@Video_obj@openfl@hxcodec@@QAEHXZ)
fe7c07a1_Video.obj : error LNK2019: unresolved external symbol _libvlc_audio_set_volume referenced in function "public: int __thiscall hxcodec::openfl::Video_obj::set_volume(int)" (?set_volume@Video_obj@openfl@hxcodec@@QAEHH@Z)
fe7c07a1_Video.obj : error LNK2019: unresolved external symbol _libvlc_audio_get_channel referenced in function "public: int __thiscall 
hxcodec::openfl::Video_obj::get_channel(void)" (?get_channel@Video_obj@openfl@hxcodec@@QAEHXZ)
fe7c07a1_Video.obj : error LNK2019: unresolved external symbol _libvlc_audio_set_channel referenced in function "public: int __thiscall 
hxcodec::openfl::Video_obj::set_channel(int)" (?set_channel@Video_obj@openfl@hxcodec@@QAEHH@Z)
fe7c07a1_Video.obj : error LNK2019: unresolved external symbol _libvlc_audio_get_delay referenced in function "public: int __thiscall hxcodec::openfl::Video_obj::get_delay(void)" (?get_delay@Video_obj@openfl@hxcodec@@QAEHXZ)
fe7c07a1_Video.obj : error LNK2019: unresolved external symbol _libvlc_audio_set_delay referenced in function "public: int __thiscall hxcodec::openfl::Video_obj::set_delay(int)" (?set_delay@Video_obj@openfl@hxcodec@@QAEHH@Z)
ApplicationMain.exe : fatal error LNK1120: 38 unresolved externals

**Comment by Karim-Akra** [comment]
sorry i forgot to put which libs im using
haxe: [4.2.5]
actuate: [1.8.9]
box2d: [1.2.3]
extension-androidtools: [1.8.2]
flixel-addons: [3.1.1]
flixel-demos: [2.9.2]
flixel-templates: [2.6.6]
flixel-tools: [1.5.1]
flixel-ui: [2.5.0]
flixel: [5.3.1]
haxelib: [4.1.0]
hscript: [2.5.0]
hxCodec: [3.0.1]
hxcpp-debug-server: [1.2.4]
hxcpp: [4.2.1]
hxjsonast: [1.1.0]
layout: [1.2.1]
lime-samples: [7.0.0]
lime: [7.9.0]
linc_luajit: [git]
openfl-samples: [8.7.0]
openfl: [9.1.0]
systools: [1.1.0]
tjson: [1.4.0]

**Comment by MAJigsaw77** [comment]
The latest version is 3.0.2 .___.

**Comment by MAJigsaw77** [comment]
But I think, you should remove the export folder and compile again

**Comment by Karim-Akra** [comment]
> But I think, you should remove the export folder and compile again

i updated to 3.0.2
used lime clean windows
deleted the export folder
still giving me the same error

**Comment by MAJigsaw77** [comment]
Remove the the haxelib and reinstall it

**Comment by MAJigsaw77** [comment]
Keep in mind that the lib doesn't work on windows x86

**Comment by Karim-Akra** [comment]
> Keep in mind that the lib doesn't work on windows x86

PLEASE KILL ME I REALIZED I WAS COMPILING TO 32 BIT HOW AM I SO FUCKING DUMB
