### ISSUE TITLE
error when compiling on macOS

### ISSUE THREAD

**Issue by NotSpring4272** [polybiusproxy/hxCodec#284]
gives this error when compiling on macOS. tried entirely rebuilding, didn't work. it's either this:

ld: file too small (length=18) file '/usr/local/lib/haxe/lib/hxCodec/3,0,2/project/vlc/dll/MacOS/lib/libvlccore.dylib' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

or this:

ld: file too small (length=14) file '/usr/local/lib/haxe/lib/hxCodec/3,0,2/project/vlc/dll/MacOS/lib/libvlc.dylib' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

<img width="565" alt="Schermata 2023-07-05 alle 13 20 11" src="https://github.com/polybiusproxy/hxCodec/assets/86001776/75d91177-2384-4f2e-bf4c-d16782e0cde0">

**Comment by MAJigsaw77** [comment]
Use the git branch because there was a issue with the released archive
