### ISSUE TITLE
you can't make a flixel videosprite dispose or add a onEndReached

### ISSUE THREAD

**Issue by TheRealJake12** [polybiusproxy/hxCodec#285]
I feel like the videosprite was completely forgotten.
![image](https://github.com/polybiusproxy/hxCodec/assets/84357907/77fd777a-64b5-4576-9acb-048d8aab454a)
![image](https://github.com/polybiusproxy/hxCodec/assets/84357907/763ebc2b-2cd1-4a60-acd4-d46de603cb7d)

Latest (3.0.2) version of hxCodec
3.0.0, 3.0.1 also have the issue

**Comment by MAJigsaw77** [comment]
Use video.bitmap.onEndReached
