### ISSUE TITLE
file too small for architecture x86_64

### ISSUE THREAD

**Issue by SevenHill-CyanS** [polybiusproxy/hxCodec#288]
I am using hxCodec 3.0.2 because I am on a macbook
it give me a error
(ld: file too small (length=14) file '/usr/local/lib/haxe/lib/hxCodec/3,0,2/project/vlc/dll/MacOS/lib/libvlc.dylib' for architecture x86_64)
anybody know how to fix it?

**Comment by polybiusproxy** [comment]
> I am using hxCodec 3.0.2 because I am on a macbook it give me a error (ld: file too small (length=14) file '/usr/local/lib/haxe/lib/hxCodec/3,0,2/project/vlc/dll/MacOS/lib/libvlc.dylib' for architecture x86_64) anybody know how to fix it?

The .dylib files are broken on Haxelib. Try installing the library from the repo.

**Comment by SevenHill-CyanS** [comment]
> > I am using hxCodec 3.0.2 because I am on a macbook it give me a error (ld: file too small (length=14) file '/usr/local/lib/haxe/lib/hxCodec/3,0,2/project/vlc/dll/MacOS/lib/libvlc.dylib' for architecture x86_64) anybody know how to fix it?
> 
> The .dylib files are broken on Haxelib. Try installing the library from the repo.

sorry how?

**Comment by SevenHill-CyanS** [comment]
> > I am using hxCodec 3.0.2 because I am on a macbook it give me a error (ld: file too small (length=14) file '/usr/local/lib/haxe/lib/hxCodec/3,0,2/project/vlc/dll/MacOS/lib/libvlc.dylib' for architecture x86_64) anybody know how to fix it?
> 
> The .dylib files are broken on Haxelib. Try installing the library from the repo.

thanks!!
