### ISSUE TITLE
error on windows executable

### ISSUE THREAD

**Issue by TomyGamy** [polybiusproxy/hxCodec#292]
![image](https://github.com/polybiusproxy/hxCodec/assets/95078425/25519228-9f18-4aa2-b520-32d041a14042)
translation:
`the procedure entry point decode URI could not be located in the dynamic link library`

so when i compile the game and launch if from the exported executable, i get this error every time i load a video...
the thing is it doesn't happen when using the `lime test windows` command

**Comment by polybiusproxy** [comment]
> ![image](https://user-images.githubusercontent.com/95078425/270116988-25519228-9f18-4aa2-b520-32d041a14042.png) translation: `the procedure entry point decode URI could not be located in the dynamic link library`
> 
> so when i compile the game and launch if from the exported executable, i get this error every time i load a video... the thing is it doesn't happen when using the `lime test windows` command

Your builds are missing the 'plugins' folder.

**Comment by TomyGamy** [comment]
> > ![image](https://user-images.githubusercontent.com/95078425/270116988-25519228-9f18-4aa2-b520-32d041a14042.png) translation: `the procedure entry point decode URI could not be located in the dynamic link library`
> > so when i compile the game and launch if from the exported executable, i get this error every time i load a video... the thing is it doesn't happen when using the `lime test windows` command
> 
> Your builds are missing the 'plugins' folder.

no its not

**Comment by polybiusproxy** [comment]
Then libvlc somehow can't find a function in the libqt4_plugin DLL file.

**Comment by TomyGamy** [comment]
how can I fix it?

**Comment by polybiusproxy** [comment]
> how can I fix it?

Do you have everything in your `plugins` folder? Make sure you're not missing anything.

**Comment by TomyGamy** [comment]
ok for some reasons, removing that plugin fixed the thing...
