### ISSUE TITLE
error with playing videos on ubuntu

### ISSUE THREAD

**Issue by TheRealJake12** [polybiusproxy/hxCodec#293]
![image](https://github.com/polybiusproxy/hxCodec/assets/84357907/d5e71734-d5c4-472c-a7c5-8536f1724367)
whenever the video is about to play, the application crashes.

**Comment by MemeHovy** [comment]
according to what I found:

> Segmentation faults in C or C++ is an error that occurs when a program attempts to access a memory location it does not have permission to access. Generally, this error occurs when memory access is violated and is a type of general protection fault. Segfaults are the abbreviation for segmentation faults.

hope this info helps, because I don't have ubuntu

**Comment by Noobz4Life** [comment]
For whatever reason, deleting /usr/lib/vlc/lua seems to fix the issue, along with downgrading VLC to an older version (3.0.9 works for example)

Both of these workarounds are very far from being ideal, but might help narrow it down a bit.

I also experimented deleting every folder in /usr/lib/vlc/lua to see if there was a specific one causing it, but it seems like every folder causes it, so it's probably VLC failing to load lua plugins if I had to guess.

**Comment by JonnycatMeow** [comment]
i have made a lib-fetch and it has the dynamic libs https://github.com/JonnycatMeow/lib-fetch/releases/download/libvlc/linux-3.0.18.dynamic.zip

**Comment by TheRealJake12** [comment]
> i have made a lib-fetch and it has the [dynamic-libs](https://github.com/JonnycatMeow/lib-fetch/releases/download/libvlc/linux-3.0.18.dynamic.zip) but i don't know how to setup the libvlc.so and the libvlccore.so

what do I do with these? (I'm new to linux kinda)

**Comment by Noobz4Life** [comment]
Ok, sorry for my previous comment being somewhat a mislead, but I found that this issue only occurs on the develop branch as well.

**Comment by JonnycatMeow** [comment]
well its because the path for the libs is wrong and im kinda to lazy to fix it
