### ISSUE TITLE
[Question] A way to not include plugins

### ISSUE THREAD

**Issue by T1mL3arn** [polybiusproxy/hxCodec#298]
I noticed that exported folder contains a lot of dll files in `plugins`. Are all of them necessary? Is it possible to get rid of things that aren't needed?

**Comment by JonnycatMeow** [comment]
yes you need those plugins in order to play video or do certain things with videos

**Comment by JonnycatMeow** [comment]
for mac its a requirement that you need to have those plugins

**Comment by JonnycatMeow** [comment]
this issue has been considered answered I am closing it now
