### ISSUE TITLE
i have a question 

### ISSUE THREAD

**Issue by ghost** [polybiusproxy/hxCodec#47]
how do you fix this error 
source/PlayState.hx:297: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead  

but it only shows thats when i build some mods because usually when you build it, it will show the error like the lib thing then it will show the error

**Comment by polybiusproxy** [comment]
That isn't an error, it's a warning, and it doesn't cause any problems in the game, it will build normally.
Plus, that warning isn't from this library, but from a deprecated function in HaxeFlixel.
