### ISSUE TITLE
Support for macOS?

### ISSUE THREAD

**Issue by ghost** [polybiusproxy/hxCodec#67]
```
In file included from ./src/vlc/VlcBitmap.cpp:127:
/Users//Downloads/ThePissedFuckingMummy-main/source/vlc/cpp/src/LibVLC.cpp:58:2: warning: deleting pointer to incomplete type 'libvlc_instance_t' may cause undefined behavior [-Wdelete-incomplete]
        delete libVlcInstance;
        ^      ~~~~~~~~~~~~~~
/Users//Downloads/ThePissedFuckingMummy-main/source/vlc/cpp/include/vlc/libvlc_structures.h:44:16: note: forward declaration of 'libvlc_instance_t'
typedef struct libvlc_instance_t libvlc_instance_t;
               ^
In file included from ./src/vlc/VlcBitmap.cpp:127:
/Users//Downloads/ThePissedFuckingMummy-main/source/vlc/cpp/src/LibVLC.cpp:59:2: warning: deleting pointer to incomplete type 'libvlc_media_t' may cause undefined behavior [-Wdelete-incomplete]
        delete libVlcMediaItem;
        ^      ~~~~~~~~~~~~~~~
/Users//Downloads/ThePissedFuckingMummy-main/source/vlc/cpp/include/vlc/libvlc_media.h:45:16: note: forward declaration of 'libvlc_media_t'
typedef struct libvlc_media_t libvlc_media_t;
               ^
In file included from ./src/vlc/VlcBitmap.cpp:127:
/Users/jonathangomez/Downloads/ThePissedFuckingMummy-main/source/vlc/cpp/src/LibVLC.cpp:60:2: warning: deleting pointer to incomplete type 'libvlc_media_player_t' may cause undefined behavior [-Wdelete-incomplete]
        delete libVlcMediaPlayer;
        ^      ~~~~~~~~~~~~~~~~~
/Users/jonathangomez/Downloads/ThePissedFuckingMummy-main/source/vlc/cpp/include/vlc/libvlc_media_player.h:49:16: note: forward declaration of 'libvlc_media_player_t'
typedef struct libvlc_media_player_t libvlc_media_player_t;
               ^
In file included from ./src/vlc/VlcBitmap.cpp:127:
/Users/jonathangomez/Downloads/ThePissedFuckingMummy-main/source/vlc/cpp/src/LibVLC.cpp:240:9: warning: 'libvlc_video_get_width' is deprecated [-Wdeprecated-declarations]
        return libvlc_video_get_width(libVlcMediaPlayer);
               ^
/Users/jonathangomez/Downloads/ThePissedFuckingMummy-main/source/vlc/cpp/include/vlc/libvlc_media_player.h:967:1: note: 'libvlc_video_get_width' has been explicitly marked deprecated here
LIBVLC_DEPRECATED LIBVLC_API
^
/Users/jonathangomez/Downloads/ThePissedFuckingMummy-main/source/vlc/cpp/include/vlc/libvlc.h:54:43: note: expanded from macro 'LIBVLC_DEPRECATED'
# define LIBVLC_DEPRECATED __attribute__((deprecated))
                                          ^
In file included from ./src/vlc/VlcBitmap.cpp:127:
/Users/jonathangomez/Downloads/ThePissedFuckingMummy-main/source/vlc/cpp/src/LibVLC.cpp:245:9: warning: 'libvlc_video_get_height' is deprecated [-Wdeprecated-declarations]
        return libvlc_video_get_height(libVlcMediaPlayer);
               ^
/Users/jonathangomez/Downloads/ThePissedFuckingMummy-main/source/vlc/cpp/include/vlc/libvlc_media_player.h:957:1: note: 'libvlc_video_get_height' has been explicitly marked deprecated here
LIBVLC_DEPRECATED LIBVLC_API
^
/Users/jonathangomez/Downloads/ThePissedFuckingMummy-main/source/vlc/cpp/include/vlc/libvlc.h:54:43: note: expanded from macro 'LIBVLC_DEPRECATED'
# define LIBVLC_DEPRECATED __attribute__((deprecated))
                                          ^
5 warnings generated.
```

**Comment by Jonnycatmeow** [comment]
idk if you can help me fix it

**Comment by Jonnycatmeow** [comment]
and im on macos

**Comment by DotWith** [comment]
> and im on macos 

The video player is only for windows

**Comment by polybiusproxy** [comment]
> > and im on macos
> 
> The video player is only for windows

Technically it can work on macOS, with a few changes on the C++ files,
+ it looks like those are just warnings.

**Comment by Jonnycatmeow** [comment]
how do i add a path to macos on vlc

**Comment by Jonnycatmeow** [comment]
?

and which vlc version do i need?

**Comment by ILuvGemz** [comment]
https://github.com/ue4plugins/VlcMedia/tree/master/ThirdParty/vlc/Mac

I think I found a library that can help… though I’m not sure how to plug it in…

**Comment by Erizur** [comment]
I was trying to get that working previously by getting the dylibs from vlc itself, however when it tried to run the code the game would just simply crash, most recent libvlccore works as I attempted to run this on linux with success.

**Comment by ILuvGemz** [comment]
Hello Erizur!

so apparently here’s an update. Apparently the .dylibs aren’t actually what we’re supposed to find. The real extension for Mac static libraries was supposedly called .a files, or libvlc.a and libvlccore.a to be exact and if I heard correctly it can only be obtained by compiling a VLC build manually. Unfortunately because I don’t have a Mac I couldn’t test if that’s even all the issues I’m afraid.

**Comment by McJonnycat** [comment]
ok bet

**Comment by McJonnycat** [comment]
i will do it please tell me what to do

**Comment by ILuvGemz** [comment]
I don’t exactly know but most likely ya gotta follow this guide.

https://wiki.videolan.org/MacOSCompile/

I’m not sure if it outputs the .a files tho.

**Comment by McJonnycat** [comment]
its ok i am doing it rn

**Comment by McJonnycat** [comment]
so it will be on my fork

**Comment by McJonnycat** [comment]
cause devs

**Comment by ILuvGemz** [comment]
Okay so are you able to compile the VLC build and find .a files?
Have you already tested your current build? If so, did it break?

**Comment by McJonnycat** [comment]
honestly i am trying so hard

**Comment by McJonnycat** [comment]
and plus i had to reinstall xcode cause they fixed it

**Comment by McJonnycat** [comment]
also where do i get the lib file at?

**Comment by ILuvGemz** [comment]
Unfortunately no such information for where the lib files are exists at the moment.

**Comment by McJonnycat** [comment]
bruh

**Comment by ILuvGemz** [comment]
I deeply apologize if all of this looks confusing. I couldn’t find anything regarding this info nearly everywhere on the internet except for a few links including the ones I gave you.

**Comment by McJonnycat** [comment]
na your good its the peoples fault for making the instructions confusing

**Comment by ILuvGemz** [comment]
Oh?…!! I thought I was in the wrong because my wording makes the info unhelpful. (Because I can’t speak proper English sometimes)

**Comment by McJonnycat** [comment]
its ok i have some friends who really can't speak english

**Comment by McJonnycat** [comment]
i wonder if i can just build it with just xcode?

**Comment by ILuvGemz** [comment]
Give it a try.

**Comment by McJonnycat** [comment]
yee ima try also do you have discord cuase if you have discord maybe you can add me discord: Jonnycat#8275

**Comment by McJonnycat** [comment]
about the vlc

**Comment by ILuvGemz** [comment]
Okay it’s 千の声 / ILuvGemz#6942 I sent it already.

**Comment by McJonnycat** [comment]
im making it rn

**Comment by Stilic** [comment]
> im making it rn

did you compiled the libs successfully?

**Comment by McJonnycat** [comment]
> > im making it rn
> 
> did you compiled the libs successfully?

i can't do it im sorry

**Comment by McJonnycat** [comment]
do dynamic library count? cause that whats in the vlc for mac

**Comment by Jrgamer4u** [comment]
tested @McJonnycat's Mac .a files with my Mac but got
```
ld: warning: ignoring file /usr/local/lib/haxe/lib/hxCodec/git/lib/vlc/lib/Mac/libvlccore.a, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x21 0x3C 0x61 0x72 0x63 0x68 0x3E 0x0D 0x0A 0x2F 0x20 0x20 0x20 0x20 0x20 0x20 )

ld: warning: ignoring file /usr/local/lib/haxe/lib/hxCodec/git/lib/vlc/lib/Mac/libvlc.a, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0xEF 0xBF 0xBD 0xEF 0xBF 0xBD 0xEF 0xBF 0xBD 0xEF 0xBF 0xBD 0x07 0x00 0x00 0x01 )
```

idk what this means, I'm using Mac 12, 64bit.

**Comment by McJonnycat** [comment]
ohhh my think yeah its broken

**Comment by McJonnycat** [comment]
but uhh if you can you have to build it using this https://wiki.videolan.org/MacOSCompile/

**Comment by McJonnycat** [comment]
like from the actual source

**Comment by Jrgamer4u** [comment]
> like from the actual source 
> 
> 

I'm too lazy to do that lmao

and i think that hxcodec is closer to libvlcpp than regular vlc but that's just a hunch

**Comment by McJonnycat** [comment]
> > like from the actual source
> 
> I'm too lazy to do that lmao
> 
> and i think that hxcodec is closer to libvlcpp than regular vlc but that's just a hunch

same

**Comment by McJonnycat** [comment]
im too lazy plus i got to do mac ports for my websites

**Comment by McJonnycat** [comment]
@Jrgamer4u so will you do the macos libs thing cause i can't do it

**Comment by Jrgamer4u** [comment]
nah

**Comment by McJonnycat** [comment]
wow

**Comment by McJonnycat** [comment]
ok

**Comment by McJonnycat** [comment]
has anyone gotten the .a vlc files?

**Comment by Jrgamer4u** [comment]
this def can be closed now

**Comment by TheKitBoi** [comment]
> this def can be closed now

the user that created the account deleted it so he can’t close the pr
So we have to wait for polybiusproxy to close this if it’s works

**Comment by MAJigsaw77** [comment]
@polybiusproxy this is solved, you can close this

**Comment by polybiusproxy** [comment]
Forgot to close it!
