### ISSUE TITLE
resume() on MP4Sprite causes random video freezes

### ISSUE THREAD

**Issue by ActualMandM** [polybiusproxy/hxCodec#99]
Trying to use `resume()` (even if the video is currently playing) will have a random chance of the video feed instantly freezing, freezing for a bit, or just not freezing at all.

https://user-images.githubusercontent.com/15317421/166094755-44ddae4c-0e7a-4b96-bfcc-b9a7ff03ecab.mp4

**Comment by polybiusproxy** [comment]
I don't know what's causing it, since on the LibVLC file, the pause and resume function both use `libvlc_media_player_pause(libVlcMediaPlayer);`

**Comment by polybiusproxy** [comment]
My guess is that upon pausing, libVLC frees the video buffer, and then tries to load it again upon resuming.

**Comment by ActualMandM** [comment]
What would happen if the resume function used `libvlc_media_player_play` instead?

**Comment by polybiusproxy** [comment]
Why don't you try?

> What would happen if the two functions used `libvlc_media_player_set_pause` instead?
> 
> ```c++
> void LibVLC::pause()
> {
> 	libvlc_media_player_set_pause(libVlcMediaPlayer, 1);
> }
> 
> void LibVLC::resume()
> {
> 	libvlc_media_player_set_pause(libVlcMediaPlayer, 0);
> }
> ```

**Comment by ActualMandM** [comment]
I've just tried it out and seems to have the same result.

**Comment by polybiusproxy** [comment]
No idea then.

**Comment by Stilic** [comment]
> Trying to use `resume()` (even if the video is currently playing) will have a random chance of the video feed instantly freezing, freezing for a bit, or just not freezing at all.
> 
>  2022-04-29_23-35-24_NotFunkin.mp4

funkin colors but da vid is broken as heck

**Comment by polybiusproxy** [comment]
Wait, could you try to pause/resume the video without pausing the whole state?
It may be that the pause substate in FNF is somehow interfering.
@ActualMandM

**Comment by ActualMandM** [comment]
Just tried it out, apparently `resume()` can both pause and unpause.

**Comment by ActualMandM** [comment]
After messing with it a bit more, this appears to just be an implementation issue on my end.

Checking for isPlaying and doing the syncing & unpausing in resyncVocals makes it work fine now, even if it's frozen for a split second after unpausing.
